/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lightoff_perez.gouges_version_console;

/**
 *
 * @author mathis
 */
import java.awt.GridLayout;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class FenetrePrincipale extends javax.swing.JFrame {
    
    private GrilleDeJeu grille;
    private int nombreCoups;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetrePrincipale.class.getName());

    private javax.swing.JPanel PanneauGrille;
    private javax.swing.JPanel PanneauBoutonsVerticaux;

    /**
     * Constructeur de la fenêtre principale
     */
    public FenetrePrincipale() {
        initComponents();

        int nbLignes = 10;
        int nbColonnes = 10;

        grille = new GrilleDeJeu(nbLignes, nbColonnes);
        initialiserPartie();

        // Configuration panneaux
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                110, 20, nbColonnes * 40, nbLignes * 40));
        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(
                20, 20, 40, nbLignes * 40));

        // Panneau des boutons verticaux
        PanneauBoutonsVerticaux.setLayout(new GridLayout(nbLignes, 1));
        for (int i = 0; i < nbLignes; i++) {
            final int indexLigne = i;
            JButton bouton_ligne = new JButton();
            bouton_ligne.addActionListener(e -> agirSurLigne(indexLigne));
            PanneauBoutonsVerticaux.add(bouton_ligne);
        }

        // Panneau de la grille
        PanneauGrille.setLayout(new GridLayout(nbLignes, nbColonnes));
        for (int i = 0; i < nbLignes; i++) {
            for (int j = 0; j < nbColonnes; j++) {
                final int li = i;
                final int co = j;
                CelluleGraphique bouton_cellule = new CelluleGraphique(grille.getMatriceCellules()[i][j], 36, 36);
                bouton_cellule.addActionListener(e -> {
                    grille.activerCelluleEtVoisines(li, co);
                    nombreCoups++;
                    rafraichirGrille();
                    verifierFinPartie();
                });
                PanneauGrille.add(bouton_cellule);
            }
        }

        this.pack();
        this.revalidate();
    }

    /** Initialise la partie avec une grille mélangée */
    public void initialiserPartie() {
        grille.eteindreToutesLesCellules();
        grille.melangerMatriceAleatoirement(10);
    }

    /** Redessine toutes les cellules de la grille */
    private void rafraichirGrille() {
        for (int i = 0; i < grille.getNbLignes(); i++) {
            for (int j = 0; j < grille.getNbColonnes(); j++) {
                PanneauGrille.getComponent(i * grille.getNbColonnes() + j).repaint();
            }
        }
    }

    /** Active toutes les cellules d'une ligne */
    private void agirSurLigne(int ligne) {
        grille.activerLigneDeCellules(ligne);
        nombreCoups++;
        rafraichirGrille();
    }

    /** Vérifie si toutes les cellules sont éteintes */
    private void verifierFinPartie() {
        if (grille.estEteinte()) {
            FenetreVictoire f = new FenetreVictoire();
            f.setVisible(true);

            for (java.awt.Component c : PanneauGrille.getComponents()) {
                c.setEnabled(false);
            }
        }
    }

    /** Méthode générée par NetBeans pour initialiser les composants */
    private void initComponents() {
        PanneauGrille = new javax.swing.JPanel();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 0, 255));
        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 400, 400));

        PanneauBoutonsVerticaux.setBackground(new java.awt.Color(255, 0, 255));
        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 40, 400));

        pack();
    }

    /** Main pour lancer l'application */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new FenetrePrincipale().setVisible(true));
    }
}
 /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanneauGrille = new javax.swing.JPanel();
        PanneauBoutonsVerticaux = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanneauGrille.setBackground(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout PanneauGrilleLayout = new javax.swing.GroupLayout(PanneauGrille);
        PanneauGrille.setLayout(PanneauGrilleLayout);
        PanneauGrilleLayout.setHorizontalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PanneauGrilleLayout.setVerticalGroup(
            PanneauGrilleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauGrille, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 400, 400));

        PanneauBoutonsVerticaux.setBackground(new java.awt.Color(255, 0, 255));

        javax.swing.GroupLayout PanneauBoutonsVerticauxLayout = new javax.swing.GroupLayout(PanneauBoutonsVerticaux);
        PanneauBoutonsVerticaux.setLayout(PanneauBoutonsVerticauxLayout);
        PanneauBoutonsVerticauxLayout.setHorizontalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PanneauBoutonsVerticauxLayout.setVerticalGroup(
            PanneauBoutonsVerticauxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        getContentPane().add(PanneauBoutonsVerticaux, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetrePrincipale().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanneauBoutonsVerticaux;
    private javax.swing.JPanel PanneauGrille;
    // End of variables declaration//GEN-END:variables
}
